# Generated by Django 5.0.9 on 2024-11-21 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0190_nested_modules"),
        ("netbox_resiliodb", "0005_alter_lcaparams_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicerolelcatypemapping",
            name="device_role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lca_mappings",
                to="dcim.devicerole",
            ),
        ),
    ]
