# Generated by Django 5.0.9 on 2024-11-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_resiliodb', '0006_alter_devicerolelcatypemapping_device_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginsettings',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pluginsettings',
            name='access_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
