# Generated by Django 5.0.9 on 2024-11-26 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0190_nested_modules"),
        ("netbox_resiliodb", "0007_pluginsettings_access_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lcaimpactdata",
            name="cache_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="impact_data",
                to="netbox_resiliodb.lcacache",
            ),
        ),
        migrations.AlterField(
            model_name="lcaimpactdata",
            name="device",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lca_impact_data",
                to="dcim.device",
            ),
        ),
    ]
