# Generated by Django 5.0.9 on 2024-11-29 15:19

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0190_nested_modules'),
        ('extras', '0121_customfield_related_object_filter'),
        ('netbox_resiliodb', '0008_alter_lcaimpactdata_cache_entry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('pool_name', models.CharField(max_length=100)),
                ('device_roles', models.ManyToManyField(blank=True, to='dcim.devicerole')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pool_mappings', to='dcim.platform')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Pool Mapping',
                'verbose_name_plural': 'Pool Mappings',
                'ordering': ('pool_name',),
            },
        ),
    ]
